[tool.pdm]

[project]
name = "dataspike"
version = "0.1.0"
description = "The official wrapper for Dataspike API"
authors = [
    {name = "Sergey Rublev", email = "sergey.rublev@dataspike.io"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
